baseURL = "https://gustavo.jasso.info"
title = "Prof. Dr. Gustavo Jasso - Mathematician"
disableKinds = ["taxonomy"]

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 2


