baseURL = "https://gustavo.jasso.info"
disableKinds = ["taxonomy"]

[params]
  vvURL = "https://math.uni-koeln.de/sites/math_career/studium/Vorlesungs-Seminarverzeichnisse/KVV_WiSe2526.pdf"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
    title = "Prof. Dr. Gustavo Jasso - Mathematician"
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 2
    title = "Prof. Dr. Gustavo Jasso - Mathematiker"

